#include "gtest/gtest.h"

#include "../ExpressionBuilder.hpp"
#include "../TptpTool/ProofPrinter.hpp"
#include "../TptpTool/TptpProofNode.hpp"

using namespace TptpTool;
using namespace ExpressionBuilder;

class ProofPrinterTest : public ::testing::Test {
protected:
    ProofPrinter printer{ ProofPrinter::Format::TSTP };

    // Helper to normalize strings (remove carriage returns for cross-platform consistency)
    std::string normalize(std::string s) {
        s.erase(std::remove(s.begin(), s.end(), '\r'), s.end());
        return s;
    }
};

// -----------------------------------------------------------------------------
// Test Group 1: File-based Nodes (Axioms/Conjectures loaded from file)
// -----------------------------------------------------------------------------

// Test 1: Simple Atom from file (Should be CNF because atoms are literals)
// Checks if 'file(...)' source is printed correctly.
TEST_F(ProofPrinterTest, FileBasedAtomIsCnf) {
    auto formula = Pred("p", { Func("a") }); // Atom p(a)
    auto node = TptpProofNode::create(
        formula,
        ProofNode::Type::PREMISE,
        "ax1",
        "test.p",
        "axiom"
    );

    std::string output = normalize(printer.toString(node));

    // Expect: cnf(ax1, axiom, p(a), file('test.p', ax1)).
    EXPECT_NE(output.find("cnf(ax1, axiom"), std::string::npos);
    EXPECT_NE(output.find("file('test.p', ax1))."), std::string::npos);
}

// Test 2: Complex Formula from file (Should be FOF)
// Checks if complex logical structures force 'fof' prefix.
TEST_F(ProofPrinterTest, FileBasedComplexFormulaIsFof) {
    // p(a) => p(a)  (Implication makes it non-CNF in simple checks)
    auto formula = Imp(Pred("p", { Func("a") }), Pred("p", { Func("a") }));
    auto node = TptpProofNode::create(
        formula,
        ProofNode::Type::PREMISE,
        "f1",
        "logic.p",
        "hypothesis"
    );

    std::string output = normalize(printer.toString(node));

    // Expect: fof(f1, hypothesis, ..., file('logic.p', f1)).
    EXPECT_NE(output.find("fof(f1, hypothesis"), std::string::npos);
    EXPECT_NE(output.find("file('logic.p', f1))."), std::string::npos);
}

// Test 3: Conjecture from file
TEST_F(ProofPrinterTest, FileBasedConjecture) {
    // ![X]: p(X)
    auto formula = Forall(Var("X"), Pred("p", { Var("X") }));
    auto node = TptpProofNode::create(
        formula,
        ProofNode::Type::CONJECTURE,
        "conj",
        "prob.p",
        "conjecture"
    );

    std::string output = normalize(printer.toString(node));

    EXPECT_NE(output.find("fof(conj, conjecture"), std::string::npos);
    EXPECT_NE(output.find("file('prob.p', conj))."), std::string::npos);
}

// -----------------------------------------------------------------------------
// Test Group 2: Inference Steps (Generated by Solver)
// -----------------------------------------------------------------------------

// Test 4: Simple Inference Step (CNF)
// Checks if 'inference(...)' source is printed correctly for generated steps.
TEST_F(ProofPrinterTest, GeneratedInferenceCnf) {
    // p(X) | ~q(X) -> This is a clause
    auto formula = Or(Pred("p", { Var("X") }), Not(Pred("q", { Var("X") })));
    auto node = ProofStep::create(
        formula,
        ProofNode::Type::INFERENCE,
        "resolution",
        {} // No parents
    );

    std::string output = normalize(printer.toString(node));

    // ID should be 1 (first generated)
    // Expect: cnf(1, plain, ..., inference(resolution, [], [])).
    EXPECT_NE(output.find("cnf(1, plain"), std::string::npos);
    EXPECT_NE(output.find("inference(resolution, [], []))."), std::string::npos);
}

// Test 5: Negated Conjecture
// Checks if the specific role "negated_conjecture" is assigned correctly.
TEST_F(ProofPrinterTest, GeneratedNegatedConjecture) {
    auto formula = Not(Pred("goal")); // Literal ~goal
    auto node = ProofStep::create(
        formula,
        ProofNode::Type::NEGATED_CONJECTURE,
        "negate_conj",
        {}
    );

    std::string output = normalize(printer.toString(node));

    // Expect: cnf(1, negated_conjecture, ...).
    EXPECT_NE(output.find("cnf(1, negated_conjecture"), std::string::npos);
}

// -----------------------------------------------------------------------------
// Test Group 3: Structure & Linking (Parent-Child relationships)
// -----------------------------------------------------------------------------

// Test 6: Linear Chain (File Axiom -> Inference)
// Checks if the child correctly references the parent's name in 'inference(...)'.
TEST_F(ProofPrinterTest, ParentReference_FileToInference) {
    // Parent: Axiom 'ax1' from file (Atom p)
    auto f1 = Pred("p");
    auto parent = TptpProofNode::create(f1, ProofNode::Type::PREMISE, "ax1", "f.p", "axiom");

    // Child: Inference 'mp' resulting in q
    auto f2 = Pred("q");
    auto child = ProofStep::create(f2, ProofNode::Type::INFERENCE, "mp", { parent });

    std::string output = normalize(printer.toString(child));

    // Check presence of both lines
    EXPECT_NE(output.find("cnf(ax1, axiom"), std::string::npos);
    EXPECT_NE(output.find("cnf(1, plain"), std::string::npos);

    // Check Link: inference(mp, [], [ax1])
    EXPECT_NE(output.find("inference(mp, [], [ax1])"), std::string::npos);
}

// Test 7: Branching (Two Parents)
// Checks if list of parents [L1, L2] is formatted correctly.
TEST_F(ProofPrinterTest, ParentReference_MultipleParents) {
    auto p1 = TptpProofNode::create(Pred("a"), ProofNode::Type::PREMISE, "L1", "in.p", "lemma");
    auto p2 = TptpProofNode::create(Pred("b"), ProofNode::Type::PREMISE, "L2", "in.p", "lemma");

    auto result = ProofStep::create(
        ExpressionBuilder::False(),
        ProofNode::Type::INFERENCE,
        "res",
        { p1, p2 }
    );

    std::string output = normalize(printer.toString(result));

    // Check Link: inference(res, [], [L1, L2])
    // Note: Order might vary depending on internal storage, but both must exist
    EXPECT_NE(output.find("inference(res, [], ["), std::string::npos);
    EXPECT_NE(output.find("L1"), std::string::npos);
    EXPECT_NE(output.find("L2"), std::string::npos);
}

// -----------------------------------------------------------------------------
// Test Group 4: Edge Cases & ID Management
// -----------------------------------------------------------------------------

// Test 8: ID Collision Avoidance
// Ensures generated IDs (1, 2...) do not clash with file-provided IDs that happen to be numbers.
TEST_F(ProofPrinterTest, IdCollisionAvoidance) {
    // Node A explicitly named "1" in the file
    auto n1 = TptpProofNode::create(Pred("p"), ProofNode::Type::PREMISE, "1", "s.p", "axiom");

    // Node B generated (should skip ID "1" and get "2")
    auto n2 = ProofStep::create(Pred("q"), ProofNode::Type::INFERENCE, "rule", { n1 });

    std::string output = normalize(printer.toString(n2));

    EXPECT_NE(output.find("cnf(1, axiom"), std::string::npos); // The file node
    EXPECT_NE(output.find("cnf(2, plain"), std::string::npos); // The inference node has ID 2

    // Ensure there is NO "cnf(1, plain"
    EXPECT_EQ(output.find("cnf(1, plain"), std::string::npos);

    // Check linkage: inference(rule, [], [1])
    EXPECT_NE(output.find("inference(rule, [], [1])"), std::string::npos);
}

// Test 9: Null Pointer Safety
TEST_F(ProofPrinterTest, HandlesNullPointer) {
    EXPECT_EQ(printer.toString(nullptr), "");
}
